server:
  port: 8090

spring:
  application:
    name: app

tracing:
  url: http://jaeger-production-collector.tracing-system.svc.cluster.local:4318

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

